require("conf.monitor")
require("conf.autostart")
require("conf.environments")
require("conf.input")
require("conf.general")
require("conf.decoration")
require("conf.animations")
require("conf.layouts")
require("conf.gestures")
require("conf.misc")
require("conf.windowrules")
require("conf.binds")

-- DMS Include Configs
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
