# General Settings
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# Blurred Screenshot Background (New Style)
background {
    monitor =
    path = screenshot
    blur_passes = 5
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Input Field
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 0
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    fade_timeout = 1000
    font_family = SF Pro Display Nerd Font Regular
    placeholder_text = <i>Password</i>
    hide_input = false
    rounding = -1
    
    # Validation Colors
    check_color = rgba(255, 255, 255, 0.1)
    fail_color = rgba(255, 255, 255, 0.1)
    fail_transition = 300
    fail_text = <i>Incorrect <b>($ATTEMPTS)</b></i>
    
    # Lock Colors
    capslock_color = rgba(255, 255, 255, 0.1)
    numlock_color = rgba(255, 255, 255, 0.1)
    bothlock_color = rgba(255, 255, 255, 0.1)
    invert_numlock = false
    swap_font_color = false
    
    position = 0, -140
    halign = center
    valign = center
}

# Date Label (Centered New Style)
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(216, 222, 233, 0.70)
    font_size = 25
    font_family = SF Pro Display Nerd Font Bold
    position = 0, 350
    halign = center
    valign = center
}

# Time Label (Centered New Style)
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgba(216, 222, 233, 0.70)
    font_size = 120
    font_family = SF Pro Display Nerd Font Bold
    position = 0, 250
    halign = center
    valign = center
}

# Profile Image (New Style)
image {
    monitor =
    path = /var/lib/AccountsService/icons/$USER
    border_size = 2
    border_color = rgba(255, 255, 255, 0.65)
    size = 180
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd = 
    position = 0, 40
    halign = center
    valign = center
}

# User Name Label (Centered New Style)
label {
    monitor =
    text = $USER
    color = rgba(216, 222, 233, 0.80)
    font_size = 20
    font_family = SF Pro Display Nerd Font Bold
    position = 0, -82
    halign = center
    valign = center
}
